# Generated by Django 4.2.10 on 2024-05-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mobile_no',
            field=models.BigIntegerField(),
        ),
    ]
